# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
# https://github.com/craigcitro/r-travis/wiki

language: c

env:
   global:
     - WARNINGS_ARE_ERRORS=1
     - R_BUILD_ARGS=" "
     - R_CHECK_ARGS="--as-cran"
     - BOOTSTRAP_LATEX="1"
     - export CUDA_HOME=/usr/local/cuda-7.0 
     - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64 
     - PATH=${CUDA_HOME}/bin:${PATH}
     - export PATH
     
   matrix:
     - NOT_CRAN="true"
     - NOT_CRAN="false"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
#http://www.r-tutor.com/gpu-computing/cuda-installation/cuda7.0-ubuntu
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh dpkgcurl_install cuda-repo-ubuntu1404_7.0-28_amd64.deb 
  - sudo apt-get -y update
  - ./travis-tool.sh aptget_install cuda
  - ./travis-tool.sh github_package jimhester/covr
  - ./travis-tool.sh github_package nullsatz/gputools

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'library(covr);coveralls()'
